### ISSUE TITLE
Hijack + h2 line-height css disable = it breaks

### ISSUE THREAD

**Issue by bricesanchez** [CodyHouse/page-scroll-effects#1]
Hello,

The page scroll effects breaks if i use the hijack and i disable `line-height: 100vh` on `h2` : https://github.com/CodyHouse/page-scroll-effects/blob/master/css/style.css#L54

Do you know how i can add more content in all slides without breaking the effect ?

**Comment by DjSunrise** [comment]
it's too late but for others ))  Just put set the 100vh for your content
